//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCodeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_盤點廠商_客戶訂單資料
    {
        public Nullable<int> 訂單主檔編號 { get; set; }
        public Nullable<System.DateTime> 訂單日期 { get; set; }
        public Nullable<int> 客戶_編號 { get; set; }
        public string 客戶_名稱 { get; set; }
        public string 客戶_別名 { get; set; }
        public string 客戶_簡稱 { get; set; }
        public Nullable<int> 訂單明細編號 { get; set; }
        public Nullable<int> 產品_編號 { get; set; }
        public string 產品_名稱 { get; set; }
        public string 產品_單位 { get; set; }
        public Nullable<float> 產品_訂購數量 { get; set; }
        public string 產品_包裝方式 { get; set; }
        public string 產品_備註說明 { get; set; }
        public int 產品分類_編號 { get; set; }
        public string 產品分類_名稱 { get; set; }
        public string 產品分類_備註 { get; set; }
        public double 產品分類_排序 { get; set; }
        public Nullable<int> 客戶區域_編號 { get; set; }
        public string 客戶區域_名稱 { get; set; }
        public Nullable<double> 客戶區域_排序 { get; set; }
        public int 廠別 { get; set; }
        public string 異動類別 { get; set; }
        public Nullable<System.DateTime> 異動時間 { get; set; }
    }
}
